### ISSUE TITLE
Crash when "walking" into entity 

### ISSUE THREAD

**Issue by Griefed** [gigaherz/EyesInTheDarkness#12]
Hey there,

I've stumbled upon this one when accidentally walking into an Eyes In The Darkness entity whilst in creative mode. I was wondering whether this is actually related to Eyes In The Darkness, or if this is the result of me just using too many mods and a combination causing a problem.

> -- Head --
Thread: Render thread
Stacktrace:
	at me.swirtzly.regen.handlers.CommonEvents.lambda$onLivingHurt$1(CommonEvents.java:101) ~[?:1.0.6] {re:classloading}
	at me.swirtzly.regen.handlers.CommonEvents$$Lambda$23196/286298485.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161) ~[?:?] {re:classloading}
	at me.swirtzly.regen.handlers.CommonEvents.onLivingHurt(CommonEvents.java:69) ~[?:1.0.6] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_70_CommonEvents_onLivingHurt_LivingHurtEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:338) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70665_d(LivingEntity.java:1472) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,pl:mixin:APP:pmmo.mixins.json:LivingEntityChangeRespirationMixin,pl:mixin:APP:kubejs.mixins.json:LivingEntityMixin,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A}
	at gigaherz.eyes.entity.EyesEntity.disappear(EyesEntity.java:255) ~[?:0.7.0] {re:classloading}
	at gigaherz.eyes.entity.EyesEntity.func_82167_n(EyesEntity.java:248) ~[?:0.7.0] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_85033_bc(LivingEntity.java:2518) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,pl:mixin:APP:pmmo.mixins.json:LivingEntityChangeRespirationMixin,pl:mixin:APP:kubejs.mixins.json:LivingEntityMixin,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A}
	at gigaherz.eyes.entity.EyesEntity.func_85033_bc(EyesEntity.java:265) ~[?:0.7.0] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2457) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,pl:mixin:APP:pmmo.mixins.json:LivingEntityChangeRespirationMixin,pl:mixin:APP:kubejs.mixins.json:LivingEntityMixin,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMobEntity,pl:mixin:A}
	at net.minecraft.entity.monster.MonsterEntity.func_70636_d(SourceFile:43) ~[?:?] {re:mixin,re:classloading}
	at gigaherz.eyes.entity.EyesEntity.func_70636_d(EyesEntity.java:156) ~[?:0.7.0] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,pl:mixin:APP:pmmo.mixins.json:LivingEntityChangeRespirationMixin,pl:mixin:APP:kubejs.mixins.json:LivingEntityMixin,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMobEntity,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:192) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld$$Lambda$23147/1155890792.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: eyesinthedarkness:eyes (gigaherz.eyes.entity.EyesEntity)
	Entity ID: 58640
	Entity Name: entity.eyesinthedarkness.eyes
	Entity's Exact location: 324.50, 68.00, 288.50
	Entity's Block location: World: (324,68,288), Chunk: (at 4,4,0 in 20,18; contains blocks 320,0,288 to 335,255,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.01, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:A}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:161) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}

Complete crash-report: https://pastebin.com/k01CuFsk

Let me know if you need further information.
Thanks in advance.

Cheers,
Griefed

**Comment by gigaherz** [comment]
The crash log would point to a "Regen" mod. All the entity is doing is damage itself, and the damage event (LivingHurtEvent) handler from Regen is crashing. Without more information, I can't really fully blame them without more information, as it could be my entity is missing something they expect entities to have, but they are better equipped to figure out why the crash happened.. (I don't have time currently to figure out what their code is doing)

**Comment by Griefed** [comment]
The combination causing trouble here seemed to be a [Doctor Who Regeneration Mod](https://www.curseforge.com/minecraft/mc-mods/regeneration) and Eyes In The Darkness. Removing said Doctor Who mod and walking into an Eyes In The Darkness entity resulted in Minecraft *not* crashing. 

Thank you for your help and pointing me in the "Regen" direction. I'll go ahead and close this ticket.
Stay safe and keep up the good work.

Cheers,
Griefed
